language: ruby
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1
  - 2.0.0
  - jruby-9.1.9.0
script: "rake spec:all"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
 - gem install bundler
notifications:
  email:
    recipients:
      - sbazyl@google.com
      - dazuma@google.com
    on_success: change
    on_failure: change
